### This is the Terraform-generated dev-build.yml workflow for the ppod-dev app repository ###
name: dev Build and Deploy lambda Container
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  deploy:
    name: dev Deploy lambda Container
    uses: mitlibraries/.github/.github/workflows/lambda-shared-deploy-dev.yml@container-flows
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE: "ppod-gha-dev"
      ECR: "ppod-dev"
      FUNCTION: "ppod-dev"
